hockey_web_site/hockey_web_site/urls.py
from hockey_web_site import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('players/', include('players.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hockey_web_site/news/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', index, name='index'),
    path('news/', news, name='news'),
    path('news/club/', club_news, name='club_news'),
    path('news/<int:post_id>', show_post, name='post'),
]

hockey_web_site/players/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', players, name='players'),
    path('<int:player_id>', player_info, name='player_info'),
]

hockey_web_site/news/models.py
from django.db import models
from django.urls import reverse


class News(models.Model):
    title = models.TextField(max_length=255, verbose_name='Заголовок')
    content = models.TextField(blank=True, verbose_name='Текст статьи')
    photo = models.ImageField(
        upload_to="photos/news/%Y/%m/%d",
        verbose_name='Фото',
    )
    cat = models.ForeignKey(
        'Category',
        on_delete=models.PROTECT,
        verbose_name='Категория',
    )
    time_create = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Время создания',
    )
    is_published = models.BooleanField(
        default=False,
        verbose_name='В публикации'
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post", kwargs={"post_id": self.pk})

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ['-time_create', 'title']


class Category(models.Model):
    name = models.CharField(
        max_length=100,
        db_index=True,
        verbose_name='Категория'
    )
    slug = models.SlugField(
        max_length=255,
        unique=True,
        db_index=True,
        verbose_name='URL'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'
        ordering = ['pk']

hockey_web_site/players/models.py
from django.db import models
from django.urls import reverse


CHOICES = [
        ('Левый', 'Левый'),
        ('Правый', 'Правый'),
    ]


class Players(models.Model):
    name = models.TextField(max_length=255, verbose_name='Имя')
    surname = models.TextField(max_length=255, verbose_name='Фамилия')
    number = models.IntegerField(verbose_name='Номер игрока')
    photo = models.ImageField(
        upload_to="photos/players/%Y/%m/%d",
        verbose_name='Фото',
    )
    cat = models.ForeignKey(
        'Category',
        on_delete=models.PROTECT,
        verbose_name='Амплуа',
    )
    country = models.TextField(blank=False, verbose_name='Страна')
    height = models.IntegerField(verbose_name='Рост')
    weight = models.DecimalField(
        decimal_places=1,
        max_digits=4,
        verbose_name='Вес'
    )
    age = models.IntegerField(verbose_name='Возраст')
    grip = models.TextField(
        choices=CHOICES,
        default='Левый',
        verbose_name='Хват'
    )
    content = models.TextField(blank=True, verbose_name='Биография')
    time_create = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Время создания',
    )

    def __str__(self):
        return self.name + ' ' + self.surname

    def get_absolute_url(self):
        return reverse("player", kwargs={"player_id": self.pk})

    class Meta:
        verbose_name = 'Игрока'
        verbose_name_plural = 'Игроки'
        ordering = ['-time_create', 'name']


class Category(models.Model):
    name = models.CharField(
        max_length=100,
        db_index=True,
        verbose_name='Категория'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Амплуа'
        verbose_name_plural = 'Амплуа'
        ordering = ['pk']

hockey_web_site/news/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.core.paginator import Paginator

from .models import News, Category


def index(request):
    posts = News.objects.all()[:4]
    context = {
        'posts': posts,
        'title': 'Главная страница'
    }
    return render(request, 'news/index.html', context=context)


def news(request):
    all_posts = News.objects.all()
    paginator = Paginator(all_posts, 8)  # Разбиваем посты на страницы, по 5 постов на каждой странице
    page_number = request.GET.get('page')  # Получаем номер текущей страницы
    page_obj = paginator.get_page(page_number)  # Получаем объект текущей страницы

    context = {'page_obj': page_obj, }

    return render(request, 'news/news.html', context=context)


def club_news(request, category_slug='klub'):
    # Получаем объект категории по slug
    category = Category.objects.get(slug=category_slug)

    # Получаем все новости с указанной категорией
    all_posts = News.objects.filter(cat=category, is_published=True)
    paginator = Paginator(all_posts, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'page_obj': page_obj, }

    return render(request, 'news/club_news.html', context=context)


def show_post(request, post_id):
    post = get_object_or_404(News, id=post_id)
    return render(request, 'news/post.html', {'post': post, })

hockey_web_site/players/views.py
from django.shortcuts import render

from .models import Players, Category


def players(request):
    cats = Category.objects.all()
    context = {
        'cats': cats,
        'title': 'Страница команды'
    }
    return render(request, 'players/players.html', context=context)


def player_info(request, post_id):
    return render(request, 'news/post.html')

hockey_web_site/news/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="shortcut icon" href="{% static 'images/logo.png' %}" type="image/x-icon"/>
  <script src="{% static 'js/scripts.js'%}"></script>
  <title>{% block title %}Название не придумали{% endblock %}</title>
</head>
<body>
  {% include 'includes/header.html' %}
  {% block content %}Пока что здесь пусто{% endblock %}
  {% include 'includes/footer.html'%}
</body>
</html>

hockey_web_site/news/templates/includes/footer.html
{% load static %}
<div class="footer">
    <div class="container">
      <div class="footer-info">
        <div class="left-block">
          <a href="{% url 'index' %}" class="logo">
            <img src="{% static 'images/logo.png' %}" alt="" width="160px" height="130px">
          </a>
          <div class="contact-info">
            <a class="phone" href=”tel:+79998887766”>+7(999)888-77-66</a>
            <a href="" class="email">HCGarage@gmail.com</a>
          </div>
        </div>
        <div class="right-block">
          <a href="" class="social-link"><img src="{% static 'images/icons/vk.png' %}" alt="" width="40px" height="40px"></a>
          <a href="" class="social-link"><img src="{% static 'images/icons/telegram.png' %}" alt="" width="40px" height="40px"></a>
          <a href="" class="social-link"><img src="{% static 'images/icons/whatsapp.png' %}" alt="" width="40px" height="40px"></a>
          <a href="" class="social-link"><img src="{% static 'images/icons/youtube.png' %}" alt="" width="40px" height="40px"></a>
        </div>
      </div>
    </div>
</div>

hockey_web_site/news/templates/includes/header.html
{% load static %}
<a href="#" class="back-to-top">Вернуться наверх</a>
<div class="header">
<div class="nav-bar">
    <div class="container">
    <div class="flex-block">
        <a href="{% url 'index' %}" class="logo"><img src="{% static 'images/logo.png' %}" alt="" width="100px" height="80px"></a>
        <div class="dropdown">
        <button class="dropbtn">КЛУБ</button>
        <div class="dropdown-content">
        <a href="#">О клубе</a>
        <a href="#">История клуба</a>
        <a href="#">Руководство</a>
        </div>
    </div>
    <div class="dropdown">
        <button class="dropbtn">КОМАНДА</button>
        <div class="dropdown-content">
            <a href="{% url 'players' %}">Игроки</a>
            <a href="#">Тренерский состав</a>
        </div>
    </div>
    <div class="dropdown">
        <button class="dropbtn">НОВОСТИ</button>
        <div class="dropdown-content">
            <a href="{% url 'news' %}">Все новости</a>
            <a href="{% url 'club_news' %}">Новости клуба</a>
        </div>
    </div>
        <!-- <div class="dropdown">
        <button class="dropbtn">МЕДИА</button>
        <div class="dropdown-content">
            <a href="#">Ссылка 1</a>
            <a href="#">Ссылка 2</a>
            <a href="#">Ссылка 3</a>
        </div>
        </div> -->
    </div>
    </div>
</div>
</div>

hockey_web_site/news/templates/news/club_news.html
{% extends 'base.html' %}

{% block title %}Новости клуба{% endblock %}

{% block content %}
<div class="container">
    <h2 class="last_news">Новости клуба</h2>
    <div class="card-media_block">
        {% for post in page_obj %}
            <div class="card-media">
                <a href="{{ post.get_absolute_url }}" class="card-media_link"></a>
                <div class="card-media_img">
                    <img src="{{ post.photo.url }}" alt="">
                </div>
                <div class="card-media_bottom">
                    <p class="theme-name">{{ post.cat }}</p>
                    <p class="description">{{ post.title }}</p>
                    <p class="news-date">{{ p.time_create|date:'d E Y' }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
      <a href="?page={{ num }}" class="pagination-btn active">{{ num }}</a>
    {% else %}
      <a href="?page={{ num }}" class="pagination-btn">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="pagination-btn">Следующая</a>
        <a href="?page={{ page_obj.paginator.num_pages }}" class="pagination-btn">&raquo;</a>
    {% endif %}
</div>
{% endblock %}

hockey_web_site/news/templates/news/index.html
{% extends 'base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}
<div class="body">
    <div class="container">
      <h2 class="last_news">Последние новости</h2>
      <div class="card-media_block">
        {% for p in posts %}
            <div class="card-media">
            <a href="{{ p.get_absolute_url }}" class="card-media_link"></a>
            <div class="card-media_img">
                <img src="{{ p.photo.url }}" alt="">
            </div>
            <div class="card-media_bottom">
                <p class="theme-name">{{ p.cat }}</p>
                <p class="description">{{ p.title }}</p>
                <p class="news-date">{{ p.time_create|date:'d E Y' }}</p>
            </div>
            </div>
        {% endfor %}
      </div>
      <div class="other-news">
        <a class="news-btn" href="{% url 'news' %}">
          <p>Больше новостей</p>
        </a>
      </div>
    </div>
</div>
{% endblock%}

hockey_web_site/news/templates/news/news.html
{% extends 'base.html' %}

{% block title %}Все новости{% endblock %}

{% block content %}
<div class="container">
    <h2 class="last_news">Новости</h2>
    <div class="card-media_block">
        {% for post in page_obj %}
            <div class="card-media">
                <a href="{{ post.get_absolute_url }}" class="card-media_link"></a>
                <div class="card-media_img">
                    <img src="{{ post.photo.url }}" alt="">
                </div>
                <div class="card-media_bottom">
                    <p class="theme-name">{{ post.cat }}</p>
                    <p class="description">{{ post.title }}</p>
                    <p class="news-date">{{ post.time_create|date:'d E Y' }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
      <a href="?page={{ num }}" class="pagination-btn active">{{ num }}</a>
    {% else %}
      <a href="?page={{ num }}" class="pagination-btn">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="pagination-btn">Следующая</a>
        <a href="?page={{ page_obj.paginator.num_pages }}" class="pagination-btn">&raquo;</a>
    {% endif %}
</div>
{% endblock %}

hockey_web_site/news/templates/news/post.html
{% extends 'base.html' %}

{% block title %}{{ post.title }}{%endblock%}

{% block content %}
<div class="body">
    <div class="container">
      <h3 class="last_news">{{ post.title }}</h3>
      <p>{{ post.content|linebreaksbr  }}<p>
      <div class="other-news">
        <a class="news-btn" href="{% url 'news' %}">
          <p>Вернуться к новостям</p>
        </a>
      </div>
    </div>
</div>
{% endblock %}

hockey_web_site/news/templates/players/players.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="body">
    <div class="container">
        <div class="heading">Состав команды</div>
        <div class="cards">
            {% for cat in cats%}
                <div class="cards__title">
                    {{ cat.name }}
                </div>
                {% for player in cat.players_set.all %}
                    <div class="cards__wrapper">
                        <a href="#" class="card-player">
                            <picture class="card-player__image">
                                <img src="{{ player.photo.url }}">
                            </picture>
                            <div class="card-player__info">
                                <div class="card-player__wrapper">
                                    <div class="card-player__name">
                                        {{ player.name }}<p> </p>{{ player.surname }}
                                    </div>
                                    <div class="card-player__country">
                                        {{ player.country }}
                                    </div>
                                    <div class="card-player__number">
                                        {{ player.number }}
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}